server:
  port: 8096

# Dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_jwt?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user1
    password: password
